version: 2.1
jobs:
  sonarQube:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: npm install -g sonarqube-scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$CommUnityKey \
            -Dsonar.sources=.
workflows:
  version: 2
  sonar:
    jobs:
      - sonarQube
